In [9]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [10]:
# EXAMPLE DATA.
# Experimental drug was tested on 2100 individuals between 13 to 100 yrs of age.
# Half of the participants are undr 65yrs . Around 95% of the under 65yrs old experienced no side effects.
# 95% of the over 65yrs old experienced side effects

train_labels = []
train_samples = []

In [11]:
for i in  range(50):
  # The 5% of younger individuals who did experience side effects
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(1)

  # The 5% of older individuals who did not experience side effects
  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(0)

for i in range(1000):
  # The 5% of younger individuals who did experience side effects
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(0)

  # The 5% of older individuals who did not experience side effects
  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(1)

In [12]:
print(len(train_samples),train_samples[:50])
print(len(train_labels),train_labels[:50])

2100 [40, 89, 25, 67, 64, 83, 35, 79, 62, 98, 24, 98, 38, 74, 28, 66, 48, 65, 13, 88, 46, 90, 16, 77, 50, 82, 44, 72, 19, 99, 57, 88, 17, 73, 36, 70, 24, 68, 63, 67, 17, 87, 43, 100, 22, 94, 44, 68, 15, 97]
2100 [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]


In [13]:
train_samples = np.array(train_samples)
train_labels = np.array(train_labels)
train_samples, train_labels = shuffle(train_samples, train_labels)

In [14]:
print(('Train Samples:'), train_samples)
print(('Train Labels:'), train_labels )

Train Samples: [28 96 98 ... 97 78 83]
Train Labels: [0 1 1 ... 1 1 1]


In [15]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))
scaled_train_samples[:10]

array([[0.17241379],
       [0.95402299],
       [0.97701149],
       [0.02298851],
       [0.65517241],
       [0.71264368],
       [0.67816092],
       [0.71264368],
       [0.17241379],
       [0.71264368]])

**CREATING AN ARTIFICIAL NEURAL NETWORK**



In [16]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [18]:
model = Sequential([
    Dense(units = 16, input_shape=(1,1), activation =  'relu'),
    Dense(units =16, activation = 'relu'),
    Dense(units =2, activation= 'softmax')
])

In [19]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 1, 16)             32        
                                                                 
 dense_4 (Dense)             (None, 1, 16)             272       
                                                                 
 dense_5 (Dense)             (None, 1, 2)              34        
                                                                 
Total params: 338 (1.32 KB)
Trainable params: 338 (1.32 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Training the Model

In [21]:
model.compile(optimizer= Adam(learning_rate = 0.0001), loss ='sparse_categorical_crossentropy', metrics=['accuracy'])

In [22]:
model.fit(x= scaled_train_samples, y= train_labels, validation_split= 0.1, batch_size= 10, shuffle= True, epochs= 30, verbose= 2 )

Epoch 1/30
189/189 - 1s - loss: 0.6544 - accuracy: 0.5046 - val_loss: 0.6410 - val_accuracy: 0.5352 - 1s/epoch - 6ms/step
Epoch 2/30
189/189 - 0s - loss: 0.6357 - accuracy: 0.5157 - val_loss: 0.6191 - val_accuracy: 0.5381 - 317ms/epoch - 2ms/step
Epoch 3/30
189/189 - 0s - loss: 0.6157 - accuracy: 0.5296 - val_loss: 0.5983 - val_accuracy: 0.5429 - 293ms/epoch - 2ms/step
Epoch 4/30
189/189 - 0s - loss: 0.5935 - accuracy: 0.5289 - val_loss: 0.5741 - val_accuracy: 0.5390 - 273ms/epoch - 1ms/step
Epoch 5/30
189/189 - 0s - loss: 0.5704 - accuracy: 0.5358 - val_loss: 0.5498 - val_accuracy: 0.5419 - 197ms/epoch - 1ms/step
Epoch 6/30
189/189 - 0s - loss: 0.5464 - accuracy: 0.5281 - val_loss: 0.5238 - val_accuracy: 0.5438 - 211ms/epoch - 1ms/step
Epoch 7/30
189/189 - 0s - loss: 0.5209 - accuracy: 0.5234 - val_loss: 0.4967 - val_accuracy: 0.5438 - 196ms/epoch - 1ms/step
Epoch 8/30
189/189 - 0s - loss: 0.4946 - accuracy: 0.5387 - val_loss: 0.4691 - val_accuracy: 0.5438 - 197ms/epoch - 1ms/step
Epo

Building a test set and predicting

In [35]:
from random import randint
import numpy as np
from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler

In [23]:
test_labels= []
test_samples= []

In [34]:
# Initialize lists to store samples and labels
test_samples = []
test_labels = []

# Generate samples and labels
for i in range(10):
    # The 5% of older individuals who did not experience side effects
    random_older = randint(65, 100)
    test_samples.append(random_older)
    test_labels.append(0)

for i in range(200):
    # The 95% of younger individuals who did not experience side effects
    random_younger = randint(13, 64)
    test_samples.append(random_younger)
    test_labels.append(1)

# Convert lists to numpy arrays
test_labels = np.array(test_labels)
test_samples = np.array(test_samples)

# Shuffle the arrays
test_labels, test_samples = shuffle(test_labels, test_samples)

# Initialize scaler
scaler = StandardScaler()

# Reshape samples for scaling
scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1, 1))


In [36]:
predictions = model.predict(
    x = scaled_test_samples,
    batch_size= 10,
    verbose= 0

)

In [37]:
print(predictions[:5])

[[[0.9715473  0.02845259]]

 [[0.01573298 0.984267  ]]

 [[0.9937564  0.00624358]]

 [[0.07863201 0.92136794]]

 [[0.9963418  0.00365817]]]


In [38]:
# Rounding up predictions to get 0 or 1
rounded_predictions = np.argmax(predictions, axis= -1)
rounded_predictions[:5]

array([[0],
       [1],
       [0],
       [1],
       [0]])

Confusion Matrices for accuracy check

In [43]:
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt

In [44]:
cm = confusion_matrix(y_true= test_labels, y_pred= rounded_predictions)

In [53]:
# This function prints and plots the confusion matrix.
  # Normalization can be applied by setting 'normalize= True'

def plot_confusion_matrix(cm,
                          classes,
                          normalize= 'Confusion matrix',
                          cmap= plt.cm.Blues
                          ):
  plt.imshow(cm, interpolation= 'nearest', cmap=cmap)
  plt.title(title)
  plt.colorbar()
  tick_marks= np.arange(len(classes))
  plt.xticks(tick_marks, classes, rotation= 45)
  plt.yticks(tick_marks, classes)

  if normalize:
    cm= cm.astype('float') / cm.sum(axis= 1)[:, np.newaxis]
    print('Normalized confusion matrix')
  else:
    print('Confusion matrix, without normalization')

  print(cm)

  thresh= cm.max/2
  for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
    plt.text(j, i, cm[i, j],
             horizontalalignment= 'Centre',
             color= 'White' if cm[i, j] > thresh else 'Black')
    plt.tight_layout()
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')



In [48]:
cm_plot_labels = ['No_side_effects','Had_side_effects']

In [60]:
plot_confusion_matrix(cm= cm, classes= cm_plot_labels, title= 'Confusion_matrix')


TypeError: plot_confusion_matrix() got an unexpected keyword argument 'title'